name: Security Pipeline
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#      types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  gitleaks:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        
  anchore:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"

